# Generated by Django 6.0.4 on 2026-04-17 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Total de la Deuda')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Pendiente')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo (Con deuda)'), ('PAGADO', 'Pagado al 100%')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='clientes.cliente')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.pedido', verbose_name='Pedido asociado')),
            ],
            options={
                'verbose_name': 'Crédito / Fiado',
                'verbose_name_plural': 'Créditos y Fiados',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto del Abono')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Comprobante / Referencia')),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuenta', verbose_name='Cuenta donde ingresa el dinero')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='cartera.credito')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-fecha'],
            },
        ),
    ]
