# Generated by Django 6.0.4 on 2026-04-17 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Cuenta')),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('BANCO', 'Banco')], default='BANCO', max_length=20)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Actual (COP)')),
            ],
            options={
                'verbose_name': 'Cuenta de Tesorería',
                'verbose_name_plural': 'Cuentas de Tesorería',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto (COP)')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto / Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia_pedido', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Pedido Referencia')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tesoreria.cuenta')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
