# Generated by Django 6.0.4 on 2026-04-11 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('whatsapp', models.CharField(max_length=20, unique=True, verbose_name='WhatsApp')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=255, verbose_name='Producto')),
                ('talla', models.CharField(max_length=50, verbose_name='Talla')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('proveedor', models.CharField(max_length=255, verbose_name='Proveedor')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Costo (COP)')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Venta (COP)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente por Separar'), ('SEPARADO', 'Separado/Confirmado'), ('AGOTADO', 'Agotado'), ('RECOGIDO', 'Recogido'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pedido')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
