# Generated by Django 6.0.4 on 2026-04-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente por Separar'), ('SEPARADO', 'Separado/Confirmado'), ('AGOTADO', 'Agotado'), ('RECOGIDO', 'Recogido'), ('ENTREGADO', 'Entregado'), ('DEV_RECOGER', 'Devolución: Recoger al cliente'), ('DEV_PROVEEDOR', 'Devolución: Cambiar en proveedor'), ('DEV_ENTREGAR', 'Devolución: Entregar al cliente'), ('CANCELADO', 'Venta Cancelada / Reembolsada')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pedido'),
        ),
    ]
