# Generated by Django 6.0.4 on 2026-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagado_al_proveedor',
            field=models.BooleanField(default=False, verbose_name='¿Pagado al Proveedor?'),
        ),
    ]
