# Generated by Django 6.0.4 on 2026-05-08 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='proveedor_oficial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='clientes.proveedor'),
        ),
    ]
