# Generated by Django 6.0.4 on 2026-06-04 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_pedido_proveedor_oficial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente por Separar'), ('SEPARADO', 'Separado/Confirmado'), ('AGOTADO', 'Agotado'), ('RECOGIDO', 'Recogido'), ('EN_INVENTARIO', 'En Inventario (Bodega)'), ('ENTREGADO', 'Entregado'), ('DEV_RECOGER', 'Devolución: Recoger al cliente'), ('DEV_PROVEEDOR', 'Devolución: Cambiar en proveedor'), ('DEV_ENTREGAR', 'Devolución: Entregar al cliente'), ('CANCELADO', 'Venta Cancelada / Reembolsada')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pedido'),
        ),
    ]
